import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {blankTank,facilities,normalizeRecord,legacyNote,dateSchema,type Tank} from '../lib/atlas';
import {createWorkbook,readWorkbook,planImport} from '../lib/workbook';
import {GET,POST,DELETE} from '../app/api/records/route';
const sqlite=new DatabaseSync(':memory:');
for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync('drizzle/'+f,'utf8'));
let injectConflict=false;
const db={prepare(sql:string){let values:any[]=[];const wrap={bind(...v:any[]){values=v;return wrap;},async all(){return {results:sqlite.prepare(sql).all(...values)};},async first(){return sqlite.prepare(sql).get(...values)||null;},async run(){const r=sqlite.prepare(sql).run(...values);return {meta:{changes:Number(r.changes)}};}};return wrap;},async batch(items:any[]){if(injectConflict){sqlite.exec("UPDATE atlas_records SET version=version+1 WHERE id='test-1'");injectConflict=false;}sqlite.exec('BEGIN');try{const results=[];for(const item of items)results.push(await item.run());sqlite.exec('COMMIT');return results;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
(globalThis as any).testDatabase=db;
const request=(body:unknown,method='POST')=>new Request('https://test.local/api/records',{method,headers:{'content-type':'application/json','origin':'https://test.local','oai-authenticated-user-email':'test@example.invalid'},body:JSON.stringify(body)});
const t:Tank={...blankTank(facilities[0].id),id:'test-1',name:'TK-555',product:'Other',otherProduct:'Test product',companyProducts:[{id:'p1',name:'Primary Seal',description:'Model A',deliveryDate:'2026-09-30',reference:'PO-1'},{id:'p2',name:'Aluminum Dome Roof',description:'',deliveryDate:'2026-10-01',reference:'PO-2'}]};
let res=await POST(request({records:[t],notes:[{id:'n1',tankId:t.id,text:'First note'}]}));assert.equal(res.status,200);let saved=(await res.json() as any).record as Tank;assert.equal(saved.supply,'Yes');
let state=await (await GET()).json() as any;assert.equal(state.notes.length,1);assert.equal(state.notes[0].author,'test@example.invalid');assert.equal(state.records[0].lat,null);
const bytes=await createWorkbook(facilities,state.records,state.notes);const rows=await readWorkbook(new File([new Uint8Array(bytes)],'roundtrip.xlsx'));const plan=await planImport(rows,facilities,state.records,state.notes,'update');assert.deepEqual(plan.errors,[]);assert.equal(plan.notes.length,0);assert.equal(plan.records[0].companyProducts.length,2);assert.equal(plan.records[0].companyProducts[0].deliveryDate,'2026-09-30');
const sparse=await planImport({Tanks:[{'Facility ID':t.facilityId,'Tank Name':'TK-555','Stored Product':'','__row':'2'}]},facilities,state.records,state.notes,'update');assert.equal(sparse.records[0].otherProduct,'Test product');
const unlocated=await planImport({Tanks:[{'Facility ID':t.facilityId,'Tank Name':'TK-556','__row':'2'}]},facilities,state.records,state.notes,'update');assert.equal(unlocated.records[0].lat,null);assert.deepEqual(unlocated.errors,[]);
const invalid=await planImport({Tanks:[{'Facility ID':t.facilityId,'Tank Name':'TK-556','Fixed Roof / Cover Type':'Aluminum Dome Roof','Floating Roof Type':'External Floating Roof','__row':'2'}]},facilities,state.records,state.notes,'update');assert.ok(invalid.errors.length);
const skipped=await planImport(rows,facilities,state.records,state.notes,'skip');assert.equal(skipped.records.length,0);assert.equal(skipped.notes.length,0);
assert.equal((await POST(request({records:[{...saved,product:'Other',otherProduct:''}]}))).status,400);
assert.equal((await POST(request({records:[],notes:[{id:'n1',tankId:t.id,text:'Rewrite history'}]}))).status,409);
assert.throws(()=>sqlite.exec("UPDATE atlas_notes SET text='changed'"),/append-only/);assert.throws(()=>sqlite.exec('DELETE FROM atlas_notes'),/append-only/);
assert.equal((await DELETE(request({id:t.id,version:saved.version},'DELETE'))).status,409);
assert.equal((await POST(request({records:[t]}))).status,409);
// Race after validation must roll back the entire batch, including another new tank and its notes.
injectConflict=true;const conflict=await POST(request({records:[{...blankTank(t.facilityId),id:'test-2',name:'TK-600'},saved],notes:[{id:'n2',tankId:'test-2',text:'Must roll back'}]}));assert.equal(conflict.status,409);assert.equal(sqlite.prepare("SELECT count(*) n FROM atlas_records WHERE id='test-2'").get()!.n,0);assert.equal(sqlite.prepare("SELECT count(*) n FROM atlas_notes WHERE id='n2'").get()!.n,0);
const legacy=normalizeRecord({id:'legacy',kind:'tank',facilityId:t.facilityId,name:'TK-OLD',lat:1,lng:2,diameter:20,height:10,product:'LSRN',roof:'Sabit çatı',supply:'Var',equipment:'Seal',installed:'2020-01-02',notes:'Original note',documentUrl:'',version:1},'2026-09-30T00:00:00Z') as Tank;assert.equal(legacy.companyProducts[0].deliveryDate,'');assert.equal(legacy.legacyInstalled,'2020-01-02');assert.equal(legacy.roof,'Unknown');assert.equal(legacyNote(legacy)?.text,'Original note');
assert.equal(dateSchema.safeParse('2026-02-30').success,false);assert.equal(dateSchema.safeParse('2026-99-99').success,false);
const template=await createWorkbook(facilities,[],[],true);assert.deepEqual((await readWorkbook(new File([new Uint8Array(template)],'template.xlsx'))).Tanks,[]);
console.log('PASS: Excel round-trip, sparse updates, skip mode, unlocated tanks, roof checks, multiple deliveries, legacy preservation, immutable notes, date validation and atomic conflict rollback.');
