'use client';
import {useEffect,useRef,useState} from 'react';
import type {Map as LeafletMap,LayerGroup,TileLayer} from 'leaflet';
import type {Facility,Tank} from '@/lib/atlas';
type Props={facilities:Facility[];tanks:Tank[];selected:Facility|null;satellite:boolean;placing:boolean;onFacility:(f:Facility)=>void;onTank:(t:Tank)=>void;onPlace:(lat:number,lng:number)=>void;focus:Tank|null;};
export default function AtlasMap(props:Props){
 const div=useRef<HTMLDivElement>(null),map=useRef<LeafletMap|null>(null),layers=useRef<LayerGroup|null>(null),base=useRef<TileLayer|null>(null),live=useRef(props);live.current=props;
 const [ready,setReady]=useState(false),[failed,setFailed]=useState(false),[zoom,setZoom]=useState(6);
 useEffect(()=>{let disposed=false;import('leaflet').then(L=>{if(disposed||!div.current)return;const m=L.map(div.current,{zoomControl:false,minZoom:5,maxZoom:20}).setView([39,35],6);map.current=m;L.control.zoom({position:'bottomright'}).addTo(m);L.control.scale({position:'bottomleft',imperial:false}).addTo(m);layers.current=L.layerGroup().addTo(m);m.fitBounds([[35.7,25.4],[42.2,44.8]],{padding:[25,25]});m.on('click',e=>{if(live.current.placing)live.current.onPlace(e.latlng.lat,e.latlng.lng)});m.on('zoomend',()=>setZoom(m.getZoom()));setReady(true);});return()=>{disposed=true;map.current?.remove();map.current=null;};},[]);
 useEffect(()=>{if(!ready)return;let stop=false;import('leaflet').then(L=>{if(stop||!map.current)return;if(base.current)map.current.removeLayer(base.current);setFailed(false);const tile=props.satellite?L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:20,maxNativeZoom:19,attribution:'Tiles © Esri — Sources: Esri, Maxar, Earthstar Geographics, and the GIS User Community'}):L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,maxNativeZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors'});tile.on('tileerror',()=>setFailed(true));tile.on('tileload',()=>setFailed(false));tile.addTo(map.current);base.current=tile;});return()=>{stop=true;};},[ready,props.satellite]);
 useEffect(()=>{if(!ready||!map.current)return;const f=props.selected;if(f)map.current.flyTo([f.lat,f.lng],15,{duration:1.25});else map.current.flyToBounds([[35.7,25.4],[42.2,44.8]],{padding:[25,25],duration:1.2});},[ready,props.selected?.id]);
 useEffect(()=>{if(props.focus&&map.current)map.current.flyTo([props.focus.lat,props.focus.lng],18,{duration:.7});},[props.focus]);
 useEffect(()=>{if(!ready)return;let stop=false;import('leaflet').then(L=>{if(stop||!layers.current)return;layers.current.clearLayers();const group=layers.current;
 const safe=(s:string)=>{const e=document.createElement('span');e.textContent=s;return e.innerHTML;};
 const facilityVisual=(f:Facility)=>{
  if(f.type==='Petrokimya')return {className:'facility-marker petrochemical',html:'<span class="facility-glyph"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M10 5v7l-4 5v9h20v-9l-4-5V5"/><path d="M8 18h16M12 22h3m3 0h3"/><circle cx="16" cy="12" r="3"/></svg></span>'};
  if(f.type==='Terminal')return {className:'facility-marker storage',html:'<span class="facility-glyph"><svg viewBox="0 0 32 32" aria-hidden="true"><ellipse cx="10" cy="9" rx="6" ry="3"/><path d="M4 9v14c0 1.7 2.7 3 6 3s6-1.3 6-3V9"/><ellipse cx="22" cy="11" rx="6" ry="3"/><path d="M16 11v12c0 1.7 2.7 3 6 3s6-1.3 6-3V11"/></svg></span>'};
  return {className:'facility-marker refinery',html:'<span class="facility-glyph"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M7 27V11h7v16M18 27V6h7v21"/><path d="M5 27h22M8 15h5m6-4h5M9 8h3m8-5h3"/><path d="M10 11V8m11-2V3"/></svg></span>'};
 };
 const add=(f:Facility)=>{const visual=facilityVisual(f);const marker=L.marker([f.lat,f.lng],{title:f.name,icon:L.divIcon({className:visual.className,html:visual.html,iconSize:[38,38],iconAnchor:[19,19]})}).addTo(group).bindTooltip(safe(f.name),{permanent:zoom>=10,direction:'top',offset:[0,-20],className:'map-label'});marker.on('click',()=>live.current.onFacility(f));};
 if(zoom<10&&!props.selected){const aliaga=props.facilities.filter(f=>['star','tupras-izmir'].includes(f.id));props.facilities.filter(f=>!aliaga.includes(f)).forEach(add);if(aliaga.length)L.marker([38.805,26.93],{title:'Aliağa: 2 rafineri',icon:L.divIcon({className:'facility-marker cluster',html:'<span>2</span>',iconSize:[40,40],iconAnchor:[20,20]})}).addTo(group).bindTooltip('Aliağa · 2 rafineri',{permanent:true,direction:'top',offset:[0,-20],className:'map-label'}).on('click',()=>map.current?.flyTo([38.805,26.93],12));}else props.facilities.forEach(add);
 if(props.selected)props.tanks.filter(t=>t.facilityId===props.selected!.id).forEach(t=>{const color=t.supply==='Var'?'#007c59':t.supply==='Yok'?'#d18a25':'#637784';if(t.diameter)L.circle([t.lat,t.lng],{radius:t.diameter/2,color,weight:2,fillOpacity:.2}).addTo(group).on('click',()=>live.current.onTank(t));L.marker([t.lat,t.lng],{title:t.name,icon:L.divIcon({className:'tank-marker',html:`<span style="background:${color}"></span>`,iconSize:[22,22],iconAnchor:[11,11]})}).addTo(group).bindTooltip(safe(t.name),{permanent:zoom>=16,direction:'top',offset:[0,-10],className:'map-label tank-label'}).on('click',()=>live.current.onTank(t));});
 });return()=>{stop=true;};},[ready,props.facilities,props.tanks,props.selected,zoom]);
 return <><div ref={div} className={'atlas-map '+(props.placing?'placing':'')} aria-label="Türkiye tesis ve tank haritası"/>{failed&&<div className="tile-warning" role="status">Harita görüntüsü yüklenemedi. İnternet bağlantınızı kontrol edin veya harita katmanını değiştirin.</div>}</>;
}
