'use client';
import {useEffect,useRef,useState} from 'react';
import type {Map as LeafletMap,LayerGroup,TileLayer} from 'leaflet';
import {hasLocation,type Facility,type Tank} from '@/lib/atlas';
type Props={overviewKey:number;facilities:Facility[];tanks:Tank[];selected:Facility|null;satellite:boolean;placing:boolean;onFacility:(f:Facility)=>void;onTank:(t:Tank)=>void;onPlace:(lat:number,lng:number)=>void;focus:Tank|null;};
export default function AtlasMap(props:Props){
 const div=useRef<HTMLDivElement>(null),map=useRef<LeafletMap|null>(null),layers=useRef<LayerGroup|null>(null),base=useRef<TileLayer|null>(null),live=useRef(props);live.current=props;
 const [ready,setReady]=useState(false),[failed,setFailed]=useState(false),[zoom,setZoom]=useState(6);
 useEffect(()=>{let disposed=false;import('leaflet').then(L=>{if(disposed||!div.current)return;const m=L.map(div.current,{zoomControl:false,minZoom:0,maxZoom:20,worldCopyJump:true}).fitWorld();map.current=m;L.control.zoom({position:'bottomright'}).addTo(m);L.control.scale({position:'bottomleft',imperial:false}).addTo(m);layers.current=L.layerGroup().addTo(m);m.on('click',e=>{if(live.current.placing){const point=e.latlng.wrap();live.current.onPlace(Math.max(-85,Math.min(85,point.lat)),point.lng)}});m.on('zoomend',()=>setZoom(m.getZoom()));setReady(true);});return()=>{disposed=true;map.current?.remove();map.current=null;};},[]);
 useEffect(()=>{if(!ready)return;let stop=false;import('leaflet').then(L=>{if(stop||!map.current)return;if(base.current)map.current.removeLayer(base.current);setFailed(false);const tile=props.satellite?L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:20,maxNativeZoom:19,attribution:'Tiles © Esri — Sources: Esri, Maxar, Earthstar Geographics, and the GIS User Community'}):L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,maxNativeZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors'});tile.on('tileerror',()=>setFailed(true));tile.on('tileload',()=>setFailed(false));tile.addTo(map.current);base.current=tile;});return()=>{stop=true;};},[ready,props.satellite]);
 useEffect(()=>{if(!ready||!map.current)return;const f=props.selected;if(f)map.current.flyTo([f.lat,f.lng],15,{duration:1.25});else map.current.fitWorld({animate:true,duration:1.2});},[ready,props.selected?.id,props.overviewKey]);
 useEffect(()=>{if(props.focus&&hasLocation(props.focus)&&map.current)map.current.flyTo([props.focus.lat,props.focus.lng],18,{duration:.7});},[props.focus]);
 useEffect(()=>{if(!ready)return;let stop=false;import('leaflet').then(L=>{if(stop||!layers.current)return;layers.current.clearLayers();const group=layers.current;
 const safe=(s:string)=>{const e=document.createElement('span');e.textContent=s;return e.innerHTML;};
 const facilityVisual=(f:Facility)=>{const kind=f.type==='Petrochemical'?'petrochemical':f.type==='Terminal'?'storage':'refinery';return {className:'facility-marker pictogram '+kind,html:`<span class="facility-art ${kind}" aria-hidden="true"></span>`};};
 const add=(f:Facility)=>{const visual=facilityVisual(f);const marker=L.marker([f.lat,f.lng],{title:f.name,icon:L.divIcon({className:visual.className,html:visual.html,iconSize:[38,38],iconAnchor:[19,19]})}).addTo(group).bindTooltip(safe(f.name),{permanent:zoom>=10,direction:'top',offset:[0,-20],className:'map-label'});marker.on('click',()=>live.current.onFacility(f));};
 if(zoom<10&&!props.selected){const aliaga=props.facilities.filter(f=>['star','tupras-izmir','petkim','stad'].includes(f.id));props.facilities.filter(f=>!aliaga.includes(f)).forEach(add);if(aliaga.length)L.marker([38.805,26.93],{title:`Aliağa: ${aliaga.length} facilities`,icon:L.divIcon({className:'facility-marker cluster',html:`<span>${aliaga.length}</span>`,iconSize:[40,40],iconAnchor:[20,20]})}).addTo(group).bindTooltip(`Aliağa · ${aliaga.length} facilities`,{permanent:true,direction:'top',offset:[0,-20],className:'map-label'}).on('click',()=>map.current?.flyTo([38.805,26.93],12));}else props.facilities.forEach(add);
 if(props.selected)props.tanks.filter(hasLocation).filter(t=>t.facilityId===props.selected!.id).forEach(t=>{const color=t.supply==='Yes'?'#007c59':t.supply==='No'?'#d18a25':'#637784';if(t.diameter)L.circle([t.lat,t.lng],{radius:t.diameter/2,color,weight:2,fillOpacity:.2}).addTo(group).on('click',()=>live.current.onTank(t));L.marker([t.lat,t.lng],{title:t.name,icon:L.divIcon({className:'tank-marker',html:`<span style="background:${color}"></span>`,iconSize:[22,22],iconAnchor:[11,11]})}).addTo(group).bindTooltip(safe(t.name),{permanent:zoom>=16,direction:'top',offset:[0,-10],className:'map-label tank-label'}).on('click',()=>live.current.onTank(t));});
 });return()=>{stop=true;};},[ready,props.facilities,props.tanks,props.selected,zoom]);
 return <><div ref={div} className="atlas-map" data-placing={props.placing?'true':undefined} aria-label="World facility and tank map"/>{failed&&<div className="tile-warning" role="status">Map imagery could not load. Check your connection or switch map layers.</div>}</>;
}

