'use client';
import {useState} from 'react';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {readWorkbook,planImport,downloadWorkbook,type WorkbookRows,type ImportPlan} from '@/lib/workbook';
import type {Facility,Tank,Note} from '@/lib/atlas';
export default function ExcelPanel({open,onClose,facilities,tanks,notes,onSaved}:{open:boolean;onClose:()=>void;facilities:Facility[];tanks:Tank[];notes:Note[];onSaved:()=>Promise<void>}){
 const [rows,setRows]=useState<WorkbookRows|null>(null),[plan,setPlan]=useState<ImportPlan|null>(null),[mode,setMode]=useState<'update'|'skip'>('update'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[filename,setFilename]=useState(''),[done,setDone]=useState('');
 async function preview(data:WorkbookRows,m:'update'|'skip'){setPlan(await planImport(data,facilities,tanks,notes,m));}
 async function choose(file:File|undefined){if(!file)return;setBusy(true);setError('');setDone('');setPlan(null);setRows(null);setFilename(file.name);try{const data=await readWorkbook(file);setRows(data);await preview(data,mode);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(){if(!plan||plan.errors.length)return;setBusy(true);setError('');try{const res=await fetch('/api/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({records:plan.records,notes:plan.notes,source:'import'})});const data=await res.json() as {error?:string};if(!res.ok)throw Error(data.error);setDone(`Import saved: ${plan.records.length} tank records and ${plan.notes.length} new notes.`);setRows(null);setPlan(null);await onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Sheet open={open} onOpenChange={v=>{if(!v&&!busy)onClose();}}><SheetContent className="editor-sheet excel-sheet"><SheetHeader><SheetTitle>Excel Data Loader</SheetTitle><SheetDescription>Preview changes before saving. Blank cells preserve existing values.</SheetDescription></SheetHeader><div className="editor-form"><button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);try{await downloadWorkbook(facilities,[],[],true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Download Excel Template</button><label className="field"><span>Upload Workbook (.xlsx)</span><input disabled={busy} type="file" accept=".xlsx" onChange={e=>{void choose(e.target.files?.[0]);e.target.value='';}}/></label><label className="field"><span>When a tank already exists</span><Select disabled={busy} value={mode} onValueChange={async(v)=>{const m=v as 'update'|'skip';setMode(m);if(rows){setBusy(true);try{await preview(rows,m);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="update">Update existing tanks</SelectItem><SelectItem value="skip">Skip existing tanks and their products / notes</SelectItem></SelectContent></Select></label><p className="muted">Use existing facility names or IDs. Tank names must be unique within a facility. New tanks can have blank coordinates.</p>{filename&&<p className="muted">{filename}</p>}{busy&&<p role="status">Processing…</p>}{error&&<div className="error-box" role="alert">{error}</div>}{done&&<p className="success-box" role="status">{done}</p>}{plan&&<><h2>Import Preview</h2><p>{plan.records.length} tanks to save · {plan.notes.length} new notes · {plan.summary.filter(s=>s.action==='Skip').length} skipped</p>{!!plan.errors.length&&<div className="error-box" role="alert"><strong>Fix these errors before importing:</strong><ul>{plan.errors.map((e,i)=><li key={i}>{e}</li>)}</ul></div>}<div className="preview-table"><table><thead><tr><th>Facility</th><th>Tank</th><th>Action</th></tr></thead><tbody>{plan.summary.map((s,i)=><tr key={i}><td>{s.facility}</td><td>{s.tank}</td><td>{s.action}</td></tr>)}</tbody></table></div><button className="primary" disabled={busy||!!plan.errors.length||!(plan.records.length+plan.notes.length)} onClick={save}>Confirm Import</button></>}</div></SheetContent></Sheet>;
}
