'use client';
import {useEffect,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import {Factory,MapPinned,Plus,Search,ArrowLeft,Satellite,Map as MapIcon,RefreshCw,CloudCheck,Download,ExternalLink,Cylinder,LocateFixed,ShieldCheck,Trash2,Check,Loader2,ChevronRight} from 'lucide-react';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogAction,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {Toaster,toast} from 'sonner';
import {facilities as seed,blankTank,type Facility,type Tank,type AtlasRecord} from '@/lib/atlas';
import 'leaflet/dist/leaflet.css';
const AtlasMap=dynamic(()=>import('./atlas-map'),{ssr:false,loading:()=> <div className="map-loading"><MapPinned size={32}/><span>Türkiye haritası yükleniyor…</span></div>});
function Choice({label,value,options,onChange}:{label:string,value:string,options:string[],onChange:(v:string)=>void}){return <label className="field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger className="w-full h-11"><SelectValue/></SelectTrigger><SelectContent>{options.map(x=><SelectItem value={x} key={x}>{x}</SelectItem>)}</SelectContent></Select></label>}
function FacilityGlyph({type}:{type:Facility['type']}){if(type==='Petrokimya')return <svg className="facility-svg" viewBox="0 0 32 32" aria-hidden="true"><path d="M10 5v7l-4 5v9h20v-9l-4-5V5"/><path d="M8 18h16M12 22h3m3 0h3"/><circle cx="16" cy="12" r="3"/></svg>;if(type==='Terminal')return <svg className="facility-svg" viewBox="0 0 32 32" aria-hidden="true"><ellipse cx="10" cy="9" rx="6" ry="3"/><path d="M4 9v14c0 1.7 2.7 3 6 3s6-1.3 6-3V9"/><ellipse cx="22" cy="11" rx="6" ry="3"/><path d="M16 11v12c0 1.7 2.7 3 6 3s6-1.3 6-3V11"/></svg>;return <svg className="facility-svg" viewBox="0 0 32 32" aria-hidden="true"><path d="M7 27V11h7v16M18 27V6h7v21"/><path d="M5 27h22M8 15h5m6-4h5M9 8h3m8-5h3"/><path d="M10 11V8m11-2V3"/></svg>}
export default function Home(){
 const [facilities,setFacilities]=useState<Facility[]>(seed),[tanks,setTanks]=useState<Tank[]>([]),[selected,setSelected]=useState<Facility|null>(null),[focus,setFocus]=useState<Tank|null>(null),[satellite,setSatellite]=useState(false),[placing,setPlacing]=useState<'tank'|'facility'|null>(null),[draft,setDraft]=useState<AtlasRecord|null>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('Tümü'),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[busy,setBusy]=useState(false),[savedAt,setSavedAt]=useState(''),[confirmDelete,setConfirmDelete]=useState(false),[confirmClose,setConfirmClose]=useState(false),[dirty,setDirty]=useState(false);
 const current=useRef({facilities,tanks});current.current={facilities,tanks};
 async function load(){setLoading(true);setLoadError('');try{const res=await fetch('/api/records',{cache:'no-store'});const data=await res.json() as {records:AtlasRecord[],error?:string};if(!res.ok)throw Error(data.error);const merged=new Map(seed.map(f=>[f.id,f]));data.records.filter((r:AtlasRecord)=>r.kind==='facility').forEach((f:Facility)=>merged.set(f.id,f));setFacilities([...merged.values()]);setTanks(data.records.filter((r:AtlasRecord)=>r.kind==='tank'));setSavedAt(new Date().toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'}));}catch(e){setLoadError(e instanceof Error?e.message:'Kayıtlar yüklenemedi.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 useEffect(()=>{const before=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before);},[dirty]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')setPlacing(null)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[]);
 function choose(f:Facility){setSelected(f);setSatellite(true);setPlacing(null);setQuery('');setFilter('Tümü');setFocus(null);}
 useEffect(()=>{const ctx=(document as Document & {modelContext?:{registerTool:(t:unknown,o:unknown)=>unknown}}).modelContext;if(!ctx?.registerTool)return;const controller=new AbortController();const opts={signal:controller.signal};try{Promise.resolve(ctx.registerTool({name:'list_tank_inventory',description:'Read saved facility and tank inventory currently loaded in Tank Atlas.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>current.current},opts)).catch(console.error);Promise.resolve(ctx.registerTool({name:'open_facility_map',description:'Navigate the visible map to an existing facility without modifying records.',inputSchema:{type:'object',properties:{facilityId:{type:'string'}},required:['facilityId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:{facilityId:string})=>{const f=current.current.facilities.find(f=>f.id===input?.facilityId);if(!f)throw Error('Unknown facility');choose(f);return {facilityId:f.id};}},opts)).catch(console.error);}catch(e){console.error(e)}return()=>controller.abort();},[]);
 function edit(record:AtlasRecord){setDraft({...record});setDirty(false);setPlacing(null);}
 function update(key:string,value:unknown){setDraft(d=>d?({...d,[key]:value} as AtlasRecord):null);setDirty(true);}
 function close(){if(busy)return;if(dirty)setConfirmClose(true);else setDraft(null);}
 function place(lat:number,lng:number){if(placing==='tank'&&selected){setDraft(blankTank(selected.id,lat,lng));setDirty(true);}else if(placing==='facility'){setDraft({id:crypto.randomUUID(),kind:'facility',name:'',city:'',operator:'',type:'Terminal',lat,lng,version:0});setDirty(true);}setPlacing(null);}
 async function save(e:React.FormEvent){e.preventDefault();if(!draft||busy)return;setBusy(true);try{const res=await fetch('/api/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});const result=await res.json() as {record:AtlasRecord,error?:string};if(!res.ok)throw Error(result.error);const r=result.record as AtlasRecord;if(r.kind==='tank'){setTanks(v=>[...v.filter(t=>t.id!==r.id),r]);setFocus(r);}else{setFacilities(v=>[...v.filter(f=>f.id!==r.id),r]);setSelected(r);setSatellite(true);}setDirty(false);setDraft(null);setSavedAt(new Date().toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'}));toast.success('Kaydedildi. Diğer cihazlarında da açabilirsin.');}catch(e){toast.error(e instanceof Error?e.message:'Kaydedilemedi.',{duration:9000});}finally{setBusy(false);}}
 async function remove(){if(!draft||draft.kind!=='tank')return;setBusy(true);try{const res=await fetch('/api/records',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:draft.id,version:draft.version})});const data=await res.json() as {records:AtlasRecord[],error?:string};if(!res.ok)throw Error(data.error);setTanks(v=>v.filter(t=>t.id!==draft.id));setDraft(null);setDirty(false);toast.success('Tank kaydı silindi.');}catch(e){toast.error(e instanceof Error?e.message:'Silinemedi.');}finally{setBusy(false);}}
 function exportData(){const body=JSON.stringify({exportedAt:new Date().toISOString(),facilities,tanks},null,2);const url=URL.createObjectURL(new Blob([body],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='tank-atlas-'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(url);}
 const ft=tanks.filter(t=>t.facilityId===selected?.id),matches=(text:string)=>text.toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr'));const shownTanks=ft.filter(t=>matches(t.name+' '+t.product+' '+t.equipment)&&(filter==='Tümü'||t.supply===filter));const shownFacilities=facilities.filter(f=>matches(f.name+' '+f.city+' '+f.operator));
 return <main className="app-shell"><Toaster position="top-center" richColors/><header className="topbar"><a className="brand" href="/" aria-label="Tank Atlas ana sayfa"><span className="brand-icon"><Cylinder size={24}/></span><span>TANK<span className="brand-light">ATLAS</span><small>TESİS & TANK ENVANTERİ</small></span></a><div className="top-meta"><ShieldCheck size={15}/><span>Özel çalışma alanı</span></div><div className="top-actions"><button className="icon-button" onClick={load} disabled={loading||busy} title="Kayıtları yenile" aria-label="Kayıtları yenile"><RefreshCw size={18} className={loading?'spin':''}/></button><button className="export-button" onClick={exportData} disabled={loading||!!loadError}><Download size={16}/><span>Dışa aktar</span></button><span className="avatar">BÖ</span></div></header>
 <div className="workspace"><aside className="inventory"><div className="inventory-top"><div className="eyebrow">{selected?'TESİS GÖRÜNÜMÜ':'TÜRKİYE / PORTFÖY'}</div>{selected?<><button className="back" onClick={()=>{setSelected(null);setSatellite(false);setQuery('');setPlacing(null)}}><ArrowLeft size={15}/>Tüm tesisler</button><h1>{selected.name}</h1><p className="muted">{selected.city} · {selected.operator}</p></>:<><h1>Tesislerim</h1><p className="muted">Haritadan seç. Tankları keşfet.</p></>}
 <div className="summary"><div><strong>{selected?ft.length:facilities.length}</strong><span>{selected?'Kayıtlı tank':'Tesis'}</span></div><div><strong>{selected?ft.filter(t=>t.supply==='Var').length:tanks.length}</strong><span>{selected?'Ürünümüz var':'Kayıtlı tank'}</span></div></div>
 <label className="search"><Search size={18}/><input aria-label={selected?'Tank ara':'Tesis ara'} placeholder={selected?'Tank, ürün veya ekipman ara':'Tesis, şehir veya işletmeci ara'} value={query} onChange={e=>setQuery(e.target.value)}/></label>
 {selected&&<div className="filter-row">{['Tümü','Var','Yok','Bilinmiyor'].map(v=><button key={v} className={filter===v?'active':''} onClick={()=>setFilter(v)}>{v==='Var'?'Ürünümüz var':v==='Yok'?'Yok':v}</button>)}</div>}
 </div><div className="inventory-list">{loadError&&<div className="error-box" role="alert">{loadError}<button onClick={load}>Tekrar dene</button></div>}
 {!selected?shownFacilities.map((f,i)=><button key={f.id} className="facility-card" onClick={()=>choose(f)}><span className={'facility-symbol '+(f.type==='Rafineri'?'refinery':f.type==='Petrokimya'?'petrochemical':'storage')}><FacilityGlyph type={f.type}/></span><span className="card-copy"><small>{f.operator.toLocaleUpperCase('tr')}<span>{f.type}</span></small><strong>{f.name.replace('Tüpraş ','')}</strong><span>{f.city}</span></span><ChevronRight size={16}/></button>):shownTanks.map(t=><button key={t.id} className="tank-card" onClick={()=>{setFocus(t);edit(t)}}><span className={'tank-dot '+(t.supply==='Var'?'supplied':t.supply==='Yok'?'not-supplied':'')}><Cylinder size={21}/></span><span className="card-copy"><strong>{t.name}</strong><span>{t.product||'Ürün belirtilmedi'}{t.diameter?' · Ø '+t.diameter+' m':''}</span><small>{t.supply==='Var'?(t.equipment||'Şirket ürünümüz var'):t.supply==='Yok'?'Şirket ürünümüz yok':'Ekipman bilgisi bekleniyor'}</small></span><ChevronRight size={16}/></button>)}
 {selected&&ft.length===0&&!loading&&!loadError&&<div className="empty-state"><Cylinder size={38}/><h2>İlk tankını işaretle</h2><p>Uydu görüntüsünde tank sahasına yaklaş. “Tank ekle” düğmesine basıp tankın merkezini seç.</p><span>Tank numaraları ve ekipman bilgileri senin kayıtlarınla oluşacak.</span></div>}
 {((!selected&&shownFacilities.length===0)||(selected&&ft.length>0&&shownTanks.length===0))&&<p className="no-result">Aramana uygun kayıt bulunamadı.</p>}
 </div><div className="inventory-bottom">{selected?<><button className="primary" disabled={loading||!!loadError} onClick={()=>{setPlacing('tank');setSatellite(true)}}><Plus size={19}/>Tank ekle</button><div className="facility-links"><button onClick={()=>edit(facilities.find(f=>f.id===selected.id)||selected)}>Tesis bilgilerini düzenle</button><a target="_blank" rel="noopener noreferrer" href={`https://www.google.com/maps/@?api=1&map_action=map&center=${selected.lat},${selected.lng}&zoom=16&basemap=satellite`} title="Google Maps'te aç"><ExternalLink size={16}/></a></div></>:<button className="secondary" disabled={loading||!!loadError} onClick={()=>setPlacing('facility')}><Plus size={18}/>Tesis / terminal ekle</button>}<div className="sync-status"><CloudCheck size={15}/><span>{loading?'Kayıtlar yükleniyor…':loadError?'Bağlantı kurulamadı':`Bulut kayıtları güncel · ${savedAt}`}</span></div></div></aside>
 <section className="map-stage"><AtlasMap facilities={facilities} tanks={tanks} selected={selected} satellite={satellite} placing={!!placing} onFacility={choose} onTank={t=>{setFocus(t);edit(t)}} onPlace={place} focus={focus}/><div className="map-top"><div className="breadcrumb"><MapPinned size={17}/><button onClick={()=>{setSelected(null);setSatellite(false);setPlacing(null)}}>Türkiye</button>{selected&&<><ChevronRight size={14}/><span>{selected.name}</span></>}</div><div className="layer-switch"><button className={!satellite?'active':''} onClick={()=>setSatellite(false)}><MapIcon size={16}/>Harita</button><button className={satellite?'active':''} onClick={()=>setSatellite(true)}><Satellite size={16}/>Uydu</button></div></div>
 {placing?<div className="placement-banner" role="status"><LocateFixed size={19}/><span>{placing==='tank'?'Tankın merkezine tıkla':'Yeni tesisin konumuna tıkla'}</span><button onClick={()=>setPlacing(null)}>İptal</button></div>:!selected&&<div className="map-caption"><span className="eyebrow">TÜRKİYE ENERJİ HARİTASI</span><h2>Tesisten tanka,<br/>tek bir haritada.</h2><p>Bir rafineriyi seçerek uydu görünümüne geç.</p></div>}
 <div className="map-legend">{selected?<><span><i className="green"/>Ürünümüz var</span><span><i className="amber"/>Yok</span><span><i/>Bilinmiyor</span></>:<><span className="legend-facility refinery"><FacilityGlyph type="Rafineri"/>Rafineri</span><span className="legend-facility petrochemical"><FacilityGlyph type="Petrokimya"/>Petrokimya</span><span className="legend-facility storage"><FacilityGlyph type="Terminal"/>Depolama</span><span className="legend-separator"/>{facilities.length} tesis</>}</div>
 </section></div>
 <Sheet open={!!draft} onOpenChange={open=>{if(!open)close()}}><SheetContent className="editor-sheet sm:max-w-[480px] w-full overflow-y-auto" onInteractOutside={e=>{e.preventDefault();close()}}><SheetHeader><span className="eyebrow">{draft?.kind==='tank'?'TANK KAYDI':'TESİS KAYDI'}</span><SheetTitle className="text-2xl">{draft?.version?draft.name:draft?.kind==='tank'?'Yeni tank':'Yeni tesis / terminal'}</SheetTitle><SheetDescription>{draft?.kind==='tank'?facilities.find(f=>f.id===draft.facilityId)?.name:'Konum ve işletme bilgileri'}</SheetDescription></SheetHeader>{draft&&<form className="editor-form" onSubmit={save}><label className="field"><span>{draft.kind==='tank'?'Tank numarası / adı':'Tesis adı'} *</span><input required maxLength={120} placeholder={draft.kind==='tank'?'Örn. TK-555':'Örn. Aliağa Terminali'} value={draft.name} onChange={e=>update('name',e.target.value)}/></label>
 {draft.kind==='facility'?<><div className="form-grid"><label className="field"><span>İşletmeci</span><input maxLength={100} value={draft.operator} onChange={e=>update('operator',e.target.value)}/></label><label className="field"><span>Şehir / ilçe</span><input maxLength={80} value={draft.city} onChange={e=>update('city',e.target.value)}/></label></div><Choice label="Tesis tipi" value={draft.type} options={['Rafineri','Terminal','Petrokimya']} onChange={v=>update('type',v)}/></>:<><div className="form-grid"><label className="field"><span>Çap (m)</span><input type="number" step="0.01" min="0.01" max="1000" placeholder="Bilinmiyor" value={draft.diameter??''} onChange={e=>update('diameter',e.target.value?Number(e.target.value):null)}/></label><label className="field"><span>Yükseklik (m)</span><input type="number" step="0.01" min="0.01" max="1000" placeholder="Bilinmiyor" value={draft.height??''} onChange={e=>update('height',e.target.value?Number(e.target.value):null)}/></label></div><label className="field"><span>Depolanan ürün</span><input maxLength={100} placeholder="Örn. Benzin, nafta, motorin" value={draft.product} onChange={e=>update('product',e.target.value)}/></label><Choice label="Çatı tipi" value={draft.roof} options={['Bilinmiyor','Sabit çatı','Dış yüzer çatı','İç yüzer çatı','Alüminyum kubbe']} onChange={v=>update('roof',v)}/><div className="equipment-section"><Choice label="Şirketimizin ürünü var mı?" value={draft.supply} options={['Bilinmiyor','Var','Yok']} onChange={v=>update('supply',v)}/><label className="field"><span>Verdiğimiz ürünler / ekipman</span><input maxLength={500} placeholder="Örn. ADR, IFR, birincil ve ikincil seal" value={draft.equipment} onChange={e=>update('equipment',e.target.value)}/></label><label className="field"><span>Montaj tarihi</span><input type="date" value={draft.installed} onChange={e=>update('installed',e.target.value)}/></label></div><label className="field"><span>Notlar</span><textarea rows={3} maxLength={5000} placeholder="Proje, sipariş, bakım veya saha notları…" value={draft.notes} onChange={e=>update('notes',e.target.value)}/></label><label className="field"><span>Doküman / fotoğraf bağlantısı</span><input type="url" placeholder="https://…" value={draft.documentUrl} onChange={e=>update('documentUrl',e.target.value)}/></label>{draft.documentUrl.startsWith('https://')&&<a className="document-link" href={draft.documentUrl} target="_blank" rel="noopener noreferrer">Bağlantıyı aç <ExternalLink size={14}/></a>}</>}
 <div className="coordinate-section"><span className="eyebrow">HARİTA KONUMU</span><div className="form-grid"><label className="field"><span>Enlem</span><input required type="number" step="any" min="-85" max="85" value={draft.lat} onChange={e=>update('lat',Number(e.target.value))}/></label><label className="field"><span>Boylam</span><input required type="number" step="any" min="-180" max="180" value={draft.lng} onChange={e=>update('lng',Number(e.target.value))}/></label></div></div><div className="form-footer"><button type="submit" className="primary" disabled={busy}>{busy?<Loader2 size={18} className="spin"/>:<Check size={18}/>} {busy?'Kaydediliyor…':'Kaydet'}</button><button type="button" className="secondary" disabled={busy} onClick={close}>Vazgeç</button>{draft.kind==='tank'&&draft.version>0&&<button type="button" className="delete-button" disabled={busy} onClick={()=>setConfirmDelete(true)}><Trash2 size={16}/>Tankı sil</button>}</div><p className="save-note">Kayıtlar hesabına bağlı çevrimiçi saklanır.</p></form>}</SheetContent></Sheet>
 <AlertDialog open={confirmDelete} onOpenChange={setConfirmDelete}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Tank kaydı silinsin mi?</AlertDialogTitle><AlertDialogDescription>{draft?.name} kaydı ve girdiğin bilgiler silinecek.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Vazgeç</AlertDialogCancel><AlertDialogAction onClick={remove}>Sil</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={confirmClose} onOpenChange={setConfirmClose}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Değişiklikler kaydedilmedi</AlertDialogTitle><AlertDialogDescription>Formu kapatırsan bu değişiklikleri kaybedersin.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Düzenlemeye devam et</AlertDialogCancel><AlertDialogAction onClick={()=>{setDraft(null);setDirty(false)}}>Değişiklikleri bırak</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </main>;
}
