'use client';
import {useEffect,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import {Factory,MapPinned,Plus,Search,ArrowLeft,Satellite,Map as MapIcon,RefreshCw,CloudCheck,Download,ExternalLink,Cylinder,LocateFixed,ShieldCheck,Trash2,Check,Loader2,ChevronRight} from 'lucide-react';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogAction,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {Toaster,toast} from 'sonner';
import {facilities as seed,blankTank,type Facility,type Tank,type AtlasRecord} from '@/lib/atlas';
import 'leaflet/dist/leaflet.css';
import TankFields from './tank-fields';
import ExcelPanel from './excel-panel';
import {downloadWorkbook} from '@/lib/workbook';
import {productLabel,equipmentLabel,recordErrors,type Note} from '@/lib/atlas';
const AtlasMap=dynamic(()=>import('./atlas-map'),{ssr:false,loading:()=> <div className="map-loading"><MapPinned size={32}/><span>Loading the Türkiye map…</span></div>});
function Choice({label,value,options,onChange}:{label:string,value:string,options:string[],onChange:(v:string)=>void}){return <label className="field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger className="w-full h-11"><SelectValue/></SelectTrigger><SelectContent>{options.map(x=><SelectItem value={x} key={x}>{x}</SelectItem>)}</SelectContent></Select></label>}
function FacilityGlyph({type}:{type:Facility['type']}){const style=type==='Petrochemical'?'petrochemical':type==='Terminal'?'storage':'refinery';return <span className={'facility-art '+style} aria-hidden="true"/>;}
export default function Home(){
 const [facilities,setFacilities]=useState<Facility[]>(seed),[tanks,setTanks]=useState<Tank[]>([]),[selected,setSelected]=useState<Facility|null>(null),[focus,setFocus]=useState<Tank|null>(null),[satellite,setSatellite]=useState(false),[placing,setPlacing]=useState<'tank'|'facility'|'tank-location'|null>(null),[draft,setDraft]=useState<AtlasRecord|null>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('All'),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[busy,setBusy]=useState(false),[savedAt,setSavedAt]=useState(''),[confirmDelete,setConfirmDelete]=useState(false),[confirmClose,setConfirmClose]=useState(false),[dirty,setDirty]=useState(false);
 const [notes,setNotes]=useState<Note[]>([]),[noteText,setNoteText]=useState(''),[noteId,setNoteId]=useState(''),[excelOpen,setExcelOpen]=useState(false),[exporting,setExporting]=useState(false);
 const current=useRef({facilities,tanks});current.current={facilities,tanks};
 async function load(){setLoading(true);setLoadError('');try{const res=await fetch('/api/records',{cache:'no-store'});const data=await res.json() as {records:AtlasRecord[],notes:Note[],error?:string};if(!res.ok)throw Error(data.error);const merged=new Map(seed.map(f=>[f.id,f]));data.records.filter((r:AtlasRecord)=>r.kind==='facility').forEach((f:Facility)=>merged.set(f.id,f));setFacilities([...merged.values()]);setTanks(data.records.filter((r:AtlasRecord)=>r.kind==='tank'));setNotes(data.notes||[]);setSavedAt(new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}));}catch(e){setLoadError(e instanceof Error?e.message:'Could not load records.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 useEffect(()=>{const before=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before);},[dirty]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')setPlacing(null)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[]);
 function choose(f:Facility){setSelected(f);setSatellite(true);setPlacing(null);setQuery('');setFilter('All');setFocus(null);}
 useEffect(()=>{const ctx=(document as Document & {modelContext?:{registerTool:(t:unknown,o:unknown)=>unknown}}).modelContext;if(!ctx?.registerTool)return;const controller=new AbortController();const opts={signal:controller.signal};try{Promise.resolve(ctx.registerTool({name:'list_tank_inventory',description:'Read saved facility and tank inventory currently loaded in Tank Atlas.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>current.current},opts)).catch(console.error);Promise.resolve(ctx.registerTool({name:'open_facility_map',description:'Navigate the visible map to an existing facility without modifying records.',inputSchema:{type:'object',properties:{facilityId:{type:'string'}},required:['facilityId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:{facilityId:string})=>{const f=current.current.facilities.find(f=>f.id===input?.facilityId);if(!f)throw Error('Unknown facility');choose(f);return {facilityId:f.id};}},opts)).catch(console.error);}catch(e){console.error(e)}return()=>controller.abort();},[]);
 function edit(record:AtlasRecord){setDraft(structuredClone(record));setNoteText('');setNoteId(crypto.randomUUID());setDirty(false);setPlacing(null);}
 function update(key:string,value:unknown){setDraft(d=>d?({...d,[key]:value} as AtlasRecord):null);setDirty(true);}
 function close(){if(busy)return;if(dirty)setConfirmClose(true);else setDraft(null);}
 function place(lat:number,lng:number){if(placing==='tank-location'){update('lat',lat);update('lng',lng);setPlacing(null);return;}setNoteText('');setNoteId(crypto.randomUUID());if(placing==='tank'&&selected){setDraft(blankTank(selected.id,lat,lng));setDirty(true);}else if(placing==='facility'){setDraft({id:crypto.randomUUID(),kind:'facility',name:'',city:'',operator:'',type:'Terminal',lat,lng,version:0});setDirty(true);}setPlacing(null);}
 async function save(e:React.FormEvent){e.preventDefault();if(!draft||busy)return;const errors=recordErrors(draft);if(errors.length){toast.error(errors.join(' '));return;}setBusy(true);try{const res=await fetch('/api/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({records:[draft],notes:draft.kind==='tank'&&noteText.trim()?[{id:noteId,tankId:draft.id,text:noteText.trim()}]:[],source:'manual'})});const result=await res.json() as {record:AtlasRecord,notes:Note[],error?:string};if(!res.ok)throw Error(result.error);const r=result.record as AtlasRecord;setNotes(v=>[...v,...(result.notes||[])]);if(r.kind==='tank'){setTanks(v=>[...v.filter(t=>t.id!==r.id),r]);setFocus(r);}else{setFacilities(v=>[...v.filter(f=>f.id!==r.id),r]);setSelected(r);setSatellite(true);}setDirty(false);setDraft(null);setSavedAt(new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}));toast.success('Saved. Available on your other devices.');}catch(e){toast.error(e instanceof Error?e.message:'Could not save.',{duration:9000});}finally{setBusy(false);}}
 async function remove(){if(!draft||draft.kind!=='tank')return;setBusy(true);try{const res=await fetch('/api/records',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:draft.id,version:draft.version})});const data=await res.json() as {records:AtlasRecord[],notes:Note[],error?:string};if(!res.ok)throw Error(data.error);setTanks(v=>v.filter(t=>t.id!==draft.id));setDraft(null);setDirty(false);toast.success('Tank deleted.');}catch(e){toast.error(e instanceof Error?e.message:'Could not delete.');}finally{setBusy(false);}}
 async function exportData(){setExporting(true);try{const res=await fetch('/api/records',{cache:'no-store'});const data=await res.json() as {records:AtlasRecord[];notes:Note[];error?:string};if(!res.ok)throw Error(data.error);const merged=new Map(seed.map(f=>[f.id,f]));data.records.filter((r:AtlasRecord)=>r.kind==='facility').forEach((f:Facility)=>merged.set(f.id,f));await downloadWorkbook([...merged.values()],data.records.filter((r:AtlasRecord)=>r.kind==='tank'),data.notes||[]);}catch(e){toast.error(e instanceof Error?e.message:'Export failed.');}finally{setExporting(false);}}

 const ft=tanks.filter(t=>t.facilityId===selected?.id),matches=(text:string)=>text.toLocaleLowerCase('en').includes(query.toLocaleLowerCase('en'));const shownTanks=ft.filter(t=>matches(t.name+' '+productLabel(t)+' '+equipmentLabel(t))&&(filter==='All'||t.supply===filter));const shownFacilities=facilities.filter(f=>matches(f.name+' '+f.city+' '+f.operator));
 return <main className="app-shell"><Toaster position="top-center" richColors/><header className="topbar"><a className="brand" href="/" aria-label="Tank Atlas home"><span className="brand-icon"><Cylinder size={24}/></span><span>TANK<span className="brand-light">ATLAS</span><small>FACILITY & TANK INVENTORY</small></span></a><div className="top-meta"><ShieldCheck size={15}/><span>Private workspace</span></div><div className="top-actions"><button className="icon-button" onClick={load} disabled={loading||busy} title="Refresh records" aria-label="Refresh records"><RefreshCw size={18} className={loading?'spin':''}/></button><button className="export-button" aria-label="Export Excel" title="Export Excel" onClick={exportData} disabled={loading||!!loadError||exporting}><Download size={16}/><span>{exporting?'Exporting…':'Export Excel'}</span></button><button className="export-button" aria-label="Import Excel" title="Import Excel" onClick={()=>setExcelOpen(true)} disabled={loading||!!loadError}><Plus size={16}/><span>Import Excel</span></button></div></header>
 <div className="workspace"><aside className="inventory"><div className="inventory-top"><div className="eyebrow">{selected?'FACILITY VIEW':'TÜRKİYE / PORTFOLIO'}</div>{selected?<><button className="back" onClick={()=>{setSelected(null);setSatellite(false);setQuery('');setPlacing(null)}}><ArrowLeft size={15}/>All facilities</button><h1>{selected.name}</h1><p className="muted">{selected.city} · {selected.operator}</p></>:<><h1>My Facilities</h1><p className="muted">Select a facility. Explore its tanks.</p></>}
 <div className="summary"><div><strong>{selected?ft.length:facilities.length}</strong><span>{selected?'Registered tanks':'Facilities'}</span></div><div><strong>{selected?ft.filter(t=>t.supply==='Yes').length:tanks.length}</strong><span>{selected?'Company products':'Registered tanks'}</span></div></div>
 <label className="search"><Search size={18}/><input aria-label={selected?'Search tanks':'Search facilities'} placeholder={selected?'Search tanks, products or equipment':'Search facilities, cities or operators'} value={query} onChange={e=>setQuery(e.target.value)}/></label>
 {selected&&<div className="filter-row">{['All','Yes','No','Unknown'].map(v=><button key={v} className={filter===v?'active':''} onClick={()=>setFilter(v)}>{v==='Yes'?'Company products':v==='No'?'No':v}</button>)}</div>}
 </div><div className="inventory-list">{loadError&&<div className="error-box" role="alert">{loadError}<button onClick={load}>Try again</button></div>}
 {!selected?shownFacilities.map((f,i)=><button key={f.id} className="facility-card" onClick={()=>choose(f)}><span className={'facility-symbol '+(f.type==='Refinery'?'refinery':f.type==='Petrochemical'?'petrochemical':'storage')}><FacilityGlyph type={f.type}/></span><span className="card-copy"><small>{f.operator.toLocaleUpperCase('en')}<span>{f.type}</span></small><strong>{f.name.replace('Tüpraş ','')}</strong><span>{f.city}</span></span><ChevronRight size={16}/></button>):shownTanks.map(t=><button key={t.id} className="tank-card" onClick={()=>{setFocus(t);edit(t)}}><span className={'tank-dot '+(t.supply==='Yes'?'supplied':t.supply==='No'?'not-supplied':'')}><Cylinder size={21}/></span><span className="card-copy"><strong>{t.name}</strong><span>{t.lat===null?'Location not set · ':''}{productLabel(t)}{t.diameter?' · Ø '+t.diameter+' m':''}</span><small>{t.supply==='Yes'?(equipmentLabel(t)||'Company products present'):t.supply==='No'?'No company products':'Equipment details unknown'}</small></span><ChevronRight size={16}/></button>)}
 {selected&&ft.length===0&&!loading&&!loadError&&<div className="empty-state"><Cylinder size={38}/><h2>Mark your first tank</h2><p>Zoom into the tank farm. Click “Add Tank”, then select the tank centre.</p><span>Add your own tank numbers and equipment details.</span></div>}
 {((!selected&&shownFacilities.length===0)||(selected&&ft.length>0&&shownTanks.length===0))&&<p className="no-result">No matching records found.</p>}
 </div><div className="inventory-bottom">{selected?<><button className="primary" disabled={loading||!!loadError} onClick={()=>{setPlacing('tank');setSatellite(true)}}><Plus size={19}/>Add Tank</button><div className="facility-links"><button onClick={()=>edit(facilities.find(f=>f.id===selected.id)||selected)}>Edit facility details</button><a target="_blank" rel="noopener noreferrer" href={`https://www.google.com/maps/@?api=1&map_action=map&center=${selected.lat},${selected.lng}&zoom=16&basemap=satellite`} title="Open in Google Maps"><ExternalLink size={16}/></a></div></>:<button className="secondary" disabled={loading||!!loadError} onClick={()=>setPlacing('facility')}><Plus size={18}/>Add Facility / Terminal</button>}<div className="sync-status"><CloudCheck size={15}/><span>{loading?'Loading records…':loadError?'Connection unavailable':`Cloud records up to date · ${savedAt}`}</span></div></div></aside>
 <section className="map-stage"><AtlasMap facilities={facilities} tanks={tanks} selected={selected} satellite={satellite} placing={!!placing} onFacility={f=>{if(placing!=='tank-location')choose(f)}} onTank={t=>{if(placing!=='tank-location'){setFocus(t);edit(t)}}} onPlace={place} focus={focus}/><div className="map-top"><div className="breadcrumb"><MapPinned size={17}/><button onClick={()=>{setSelected(null);setSatellite(false);setPlacing(null)}}>Türkiye</button>{selected&&<><ChevronRight size={14}/><span>{selected.name}</span></>}</div><div className="layer-switch"><button className={!satellite?'active':''} onClick={()=>setSatellite(false)}><MapIcon size={16}/>Map</button><button className={satellite?'active':''} onClick={()=>setSatellite(true)}><Satellite size={16}/>Satellite</button></div></div>
 {placing?<div className="placement-banner" role="status"><LocateFixed size={19}/><span>{placing!=='facility'?'Click the tank centre':'Click the new facility location'}</span><button onClick={()=>setPlacing(null)}>Cancel</button></div>:!selected&&<div className="map-caption"><span className="eyebrow">TÜRKİYE ENERGY MAP</span><h2>From facility to tank,<br/>on one map.</h2><p>Select a refinery to open the satellite view.</p></div>}
 <div className="map-legend">{selected?<><span><i className="green"/>Company products</span><span><i className="amber"/>No</span><span><i/>Unknown</span></>:<><span className="legend-facility refinery"><FacilityGlyph type="Refinery"/>Refinery</span><span className="legend-facility petrochemical"><FacilityGlyph type="Petrochemical"/>Petrochemical</span><span className="legend-facility storage"><FacilityGlyph type="Terminal"/>Storage</span><span className="legend-separator"/>{facilities.length} facilities</>}</div>
 </section></div>
 <Sheet open={!!draft&&placing!=='tank-location'} onOpenChange={open=>{if(!open)close()}}><SheetContent className="editor-sheet sm:max-w-[480px] w-full overflow-y-auto" onInteractOutside={e=>{e.preventDefault();}}><SheetHeader><span className="eyebrow">{draft?.kind==='tank'?'TANK RECORD':'FACILITY RECORD'}</span><SheetTitle className="text-2xl">{draft?.version?draft.name:draft?.kind==='tank'?'New Tank':'New Facility / Terminal'}</SheetTitle><SheetDescription>{draft?.kind==='tank'?facilities.find(f=>f.id===draft.facilityId)?.name:'Location and operator details'}</SheetDescription></SheetHeader>{draft&&<form className="editor-form" onSubmit={save}><label className="field"><span>{draft.kind==='tank'?'Tank Number / Name':'Facility Name'} *</span><input required maxLength={120} placeholder={draft.kind==='tank'?'e.g. TK-555':'e.g. Aliağa Terminal'} value={draft.name} onChange={e=>update('name',e.target.value)}/></label>
 {draft.kind==='facility'?<><div className="form-grid"><label className="field"><span>Operator</span><input maxLength={100} value={draft.operator} onChange={e=>update('operator',e.target.value)}/></label><label className="field"><span>City / District</span><input maxLength={80} value={draft.city} onChange={e=>update('city',e.target.value)}/></label></div><Choice label="Facility Type" value={draft.type} options={['Refinery','Terminal','Petrochemical']} onChange={v=>update('type',v)}/></>:<TankFields tank={draft} update={update} notes={notes.filter(n=>n.tankId===draft.id)} newNote={noteText} onNote={text=>{setNoteText(text);setDirty(true);}}/>}

 <div className="coordinate-section"><span className="eyebrow">MAP LOCATION</span>{draft.kind==='tank'&&<button type="button" className="secondary" onClick={()=>{const f=facilities.find(f=>f.id===draft.facilityId);if(f){setSelected(f);setSatellite(true);setPlacing('tank-location');}}}>Set Location on Map</button>}<div className="form-grid"><label className="field"><span>Latitude</span><input required={draft.kind==='facility'} type="number" step="any" min="-85" max="85" value={draft.lat??''} onChange={e=>update('lat',e.target.value?Number(e.target.value):null)}/></label><label className="field"><span>Longitude</span><input required={draft.kind==='facility'} type="number" step="any" min="-180" max="180" value={draft.lng??''} onChange={e=>update('lng',e.target.value?Number(e.target.value):null)}/></label></div></div><div className="form-footer"><button type="submit" className="primary" disabled={busy}>{busy?<Loader2 size={18} className="spin"/>:<Check size={18}/>} {busy?'Saving…':'Save'}</button><button type="button" className="secondary" disabled={busy} onClick={close}>Cancel</button>{draft.kind==='tank'&&draft.version>0&&<button type="button" className="delete-button" disabled={busy||notes.some(n=>n.tankId===draft.id)} title="Tanks with note history cannot be deleted" onClick={()=>setConfirmDelete(true)}><Trash2 size={16}/>Delete Tank</button>}</div><p className="save-note">Records are saved online in your private workspace.</p></form>}</SheetContent></Sheet>
 <AlertDialog open={confirmDelete} onOpenChange={setConfirmDelete}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete this tank?</AlertDialogTitle><AlertDialogDescription>{draft?.name} and its details will be deleted. Tanks with notes cannot be deleted.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={remove}>Delete</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={confirmClose} onOpenChange={setConfirmClose}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Unsaved Changes</AlertDialogTitle><AlertDialogDescription>Closing this form will discard your changes.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep Editing</AlertDialogCancel><AlertDialogAction onClick={()=>{setDraft(null);setDirty(false)}}>Discard Changes</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <ExcelPanel open={excelOpen} onClose={()=>setExcelOpen(false)} facilities={facilities} tanks={tanks} notes={notes} onSaved={load}/>
 </main>;
}

