'use client';
import { Plus, Trash2 } from 'lucide-react';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { coverTypes,floatingTypes,storedProducts,supplyTypes,recordErrors,type Tank,type Note } from '@/lib/atlas';
function Choice({label,value,options,onChange}:{label:string;value:string;options:readonly string[];onChange:(v:string)=>void}){return <label className="field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger className="w-full h-11"><SelectValue/></SelectTrigger><SelectContent>{options.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></label>;}
export default function TankFields({tank,update,notes,newNote,onNote}:{tank:Tank;update:(key:string,value:unknown)=>void;notes:Note[];newNote:string;onNote:(text:string)=>void}){
 const productUpdate=(id:string,key:string,value:string)=>update('companyProducts',tank.companyProducts.map(p=>p.id===id?{...p,[key]:value}:p));
 return <><div className="form-grid">{(['diameter','height'] as const).map(key=><label className="field" key={key}><span>{key==='diameter'?'Diameter':'Height'} (m)</span><input type="number" step="0.01" min="0.01" max="1000" placeholder="Unknown" value={tank[key]??''} onChange={e=>update(key,e.target.value?Number(e.target.value):null)}/></label>)}</div>
 <Choice label="Stored Product" value={tank.product} options={storedProducts} onChange={v=>update('product',v)}/>{tank.product==='Other'&&<label className="field"><span>Specify Product *</span><input required maxLength={100} value={tank.otherProduct} onChange={e=>update('otherProduct',e.target.value)}/></label>}
 <Choice label="Fixed Roof / Cover Type" value={tank.roof} options={coverTypes} onChange={v=>update('roof',v)}/><Choice label="Floating Roof Type" value={tank.floatingRoof} options={floatingTypes} onChange={v=>update('floatingRoof',v)}/>
 {recordErrors(tank).map(e=><p className="validation-message" key={e} role="alert">{e}</p>)}
 {(tank.legacyRoof||tank.legacyInstalled)&&<div className="legacy-info"><strong>Previous record — retained for reference</strong>{tank.legacyRoof&&<p>Original roof description: {tank.legacyRoof}</p>}{tank.legacyInstalled&&<p>Legacy installation date: {tank.legacyInstalled}. Delivery date has not been inferred.</p>}</div>}
 <section className="equipment-section"><h2>Company Products</h2>{!tank.companyProducts.length&&<Choice label="Company Products Present" value={tank.supply} options={supplyTypes} onChange={v=>update('supply',v)}/>}
 {tank.companyProducts.map((p,i)=><div className="product-entry" key={p.id}><div className="section-title"><strong>Product {i+1}</strong><button type="button" aria-label={'Remove product '+(p.name||i+1)} onClick={()=>update('companyProducts',tank.companyProducts.filter(x=>x.id!==p.id))}><Trash2 size={16}/></button></div><label className="field"><span>Product Type / Name *</span><input required maxLength={120} placeholder="e.g. Primary Seal" value={p.name} onChange={e=>productUpdate(p.id,'name',e.target.value)}/></label><label className="field"><span>Model / Description</span><input maxLength={500} value={p.description} onChange={e=>productUpdate(p.id,'description',e.target.value)}/></label><div className="form-grid"><label className="field"><span>Delivery Date</span><input type="date" value={p.deliveryDate} onChange={e=>productUpdate(p.id,'deliveryDate',e.target.value)}/></label><label className="field"><span>Project / PO Reference</span><input maxLength={150} value={p.reference} onChange={e=>productUpdate(p.id,'reference',e.target.value)}/></label></div></div>)}
 <button type="button" className="secondary" onClick={()=>update('companyProducts',[...tank.companyProducts,{id:crypto.randomUUID(),name:'',description:'',deliveryDate:'',reference:''}])}><Plus size={16}/>Add Product</button></section>
 <section className="notes-section"><h2>Notes History</h2><p className="muted">Saved notes cannot be edited or deleted. Add a new note to make a correction.</p>{notes.length?notes.map(n=><article key={n.id} className="note-entry"><div><strong>{n.noteDate||'Original date unknown'}</strong><small>{n.author}</small></div><p>{n.text}</p><small>{n.source==='legacy'?'Retained from the previous record':`Recorded ${new Date(n.createdAt).toLocaleString('en-GB',{timeZone:'Europe/Istanbul'})} (Türkiye time)${n.source==='import'?' · Excel import':''}`}</small></article>):<p className="muted">No notes yet.</p>}<label className="field"><span>Add Note</span><textarea rows={3} maxLength={5000} placeholder="Project, order, maintenance or site notes…" value={newNote} onChange={e=>onNote(e.target.value)}/></label><small>The date, time and author are recorded when you save.</small></section>
 <label className="field"><span>Document / Photo URL</span><input type="url" placeholder="https://…" value={tank.documentUrl} onChange={e=>update('documentUrl',e.target.value)}/></label>{tank.documentUrl.startsWith('https://')&&<a className="document-link" href={tank.documentUrl} target="_blank" rel="noopener noreferrer">Open document ↗</a>}</>;
}
